smartrm/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('wastebasket.urls'))
]

wastebasket/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views

app_name = 'wastebasket'
urlpatterns = [
    url(r'^$', views.home_page, name="home"),
    url(r'^wastebasket/$', views.wastebasket_list, name='wastebasket_list'),
    url(r'^wastebasket/(?P<pk>\d+)/$', views.wastebasket_detail, name='wastebasket_detail'),
    url(r'^wastebasket/new/$', views.wastebasket_new, name='wastebasket_new'),

    url(r'^task/$', views.task_list, name='task_list'),
    url(r'^task/(?P<pk>\d+)/$', views.task_detail, name='task_detail'),    
    url(r'^task/new/$', views.task_new, name='task_new'),
    url(r'^task/result/(?P<pk>\d+)/$', views.task_result, name='task_result'),
]

wastebasket/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
from .task_states import TaskState

from srm.file_operations import get_full_path


class WasteBasket(models.Model):
    name = models.CharField(max_length=50, default="WasteBasket")

    rmdir    = models.BooleanField()
    force    = models.BooleanField()
    dry_run  = models.BooleanField()

    max_size            = models.IntegerField(default=32)
    storage_time        = models.DurationField(default=datetime.timedelta(days=30))
    #wastebasket_path    = models.FilePathField(path=get_full_path('~/'), allow_files=False, allow_folders=True)
    wastebasket_path    = models.TextField(default='~/Trash')

    def __unicode__(self):
        return self.name


class Task(models.Model):
    name = models.CharField(max_length=50, default="Task")
    state = models.IntegerField(default=TaskState.CREATED)

    wastebasket = models.ForeignKey(WasteBasket)

    rmdir    = models.NullBooleanField()
    force    = models.NullBooleanField()
    dry_run  = models.NullBooleanField()

    restore = models.BooleanField()
    regex   = models.BooleanField()

    paths = models.TextField()

    def __unicode__(self):
        return self.name

wastebasket/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import WasteBasket, Task


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ('name', 'wastebasket', 
            'rmdir', 'force', 'dry_run', 
            'restore', 'regex', 'paths')


class WasteBasketForm(forms.ModelForm):

    class Meta:
        model = WasteBasket
        fields = ('name', 'rmdir', 'force', 'dry_run', 
            'max_size', 'storage_time', 'wastebasket_path')

wastebasket/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render_to_response, render, redirect
from django.views import generic
from django.views.generic import ListView

from srm.wastebasket_manager import WasteBasketManager
from srm.move_error import MoveError
from srm.file_operations import cut_leafs

from wastebasket.task_states import TaskState
from wastebasket.models import WasteBasket, Task
from wastebasket.forms import TaskForm, WasteBasketForm

import multiprocessing


def home_page(request):
    return render(request, 'wastebasket/home.html')


def wastebasket_list(request):
    wastebaskets = {
        'wastebaskets': WasteBasket.objects.order_by('name')
        }

    return render(request, 'wastebasket/wastebasket_list.html', wastebaskets)


def wastebasket_detail(request, pk):
    wastebasket = WasteBasket.objects.get(pk=int(pk))
    form = WasteBasketForm(instance=wastebasket)

    if request.method == "POST":
        form = WasteBasketForm(request.POST, instance=wastebasket)
       
        if form.is_valid():
            form.save()
            return redirect('/wastebasket/')

    wb = WasteBasketManager(
        rmdir=wastebasket.rmdir,
        force=wastebasket.force,
        dry_run=wastebasket.dry_run,
        max_size=wastebasket.max_size,
        storage_time=wastebasket.storage_time,
        wastebasket_path=wastebasket.wastebasket_path,
    )

    context = {
        'form': form,
        'wastebasket': wb,
        'wastebaskets': WasteBasket.objects.all()
        }    

    return render(request, 'wastebasket/wastebasket_detail.html', context)


def wastebasket_new(request):
    form = WasteBasketForm()

    if request.method == "POST":
        form = WasteBasketForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/wastebasket/')

    return render(request, 'wastebasket/wastebasket_new.html', {'form': form})
    

def task_list(request):
    tasks = {
        'tasks': Task.objects.order_by('name'),
    }

    return render(request, 'wastebasket/task_list.html', tasks)


def task_detail(request, pk):
    task = Task.objects.get(pk=int(pk))
    form = TaskForm(instance=task)

    if request.method == "POST":
        form = TaskForm(request.POST, instance=task)

        if form.is_valid:
            form.save()
            return redirect('/task/')

    return render(request, 'wastebasket/task_detail.html', {'form': form})
    

def task_new(request):
    form = TaskForm()

    if request.method == 'POST':
        form = TaskForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/task/')
    
    return render(request, 'wastebasket/task_new.html', {'form': form})


def task_result(request, pk):
    task = Task.objects.get(pk=pk)
    working_tasks = wastebasket_working_tasks(task.wastebasket)

    context = {}
    if working_tasks:
        context = { 'task': working_tasks[0] }
    else:
        task.state = TaskState.WORKING
        task.save()
        
        context = parallel_execution_of_task(task)

        task.state = TaskState.COMPLETED
        task.save()

    return render(request,'wastebasket/task_result.html', context)


def parallel_execution_of_task(task, num_process=None):
    mgr = multiprocessing.Manager()
    result = mgr.list()

    wb = wastebasket_from_task(task)
    paths = task.paths.split()
    
    if num_process is None:
        num_process = multiprocessing.cpu_count() * 2

    action, error_object = None, None

    if task.restore:
        action = 'Restore'

        splited_paths = [ [] for i in xrange(num_process)]
        for i in xrange(len(paths)):
            splited_paths[i % num_process].append(paths[i])

        jobs = []
        for i in xrange(num_process):
            j = multiprocessing.Process(target=restore_worker,
                                        args=(result, wb, splited_paths[i]))
            jobs.append(j)

        for j in jobs:
            j.start()

        for j in jobs:
            j.join()
    elif task.regex:
        action = 'Remove'
        result = wb.remove_regex(paths[0], search_dirs=True)
    else:
        action = 'Remove'

        while paths:
            paths, leafs = cut_leafs(*paths)

            splited_paths = [ [] for i in xrange(num_process)]
            for i in xrange(len(leafs)):
                splited_paths[i % num_process].append(leafs[i])
            
            jobs = []
            for i in xrange(num_process):
                j = multiprocessing.Process(target=remove_worker, 
                                            args=(result, wb, splited_paths[i]))
                jobs.append(j)

            for j in jobs:
                j.start()

            for j in jobs:
                j.join()
    
    context = {
        'result': result,
        'action': action,
        'error_object': error_object,
    }

    return context

def wastebasket_from_task(task):
    """Creates and returns WasteBasketManager object from task.
    Task flags overlap WasteBaskeModel flags.
    """
    wastebasket_model = task.wastebasket
   
    wb = WasteBasketManager(
        rmdir=wastebasket_model.rmdir,
        force=wastebasket_model.force,
        dry_run=wastebasket_model.dry_run,
        max_size=wastebasket_model.max_size,
        storage_time=wastebasket_model.storage_time,
        wastebasket_path=wastebasket_model.wastebasket_path,
    )

    if task.rmdir is not None:
        wb.rmdir = task.rmdir

    if task.force is not None:
        wb.force = task.force
    
    if task.dry_run is not None:
        wb.dry_run = task.dry_run

    return wb


def wastebasket_working_tasks(wastebasket_model):
    """Checks if wastebasket_model has a working tasks.
    Returns the list of running task.
    """
    tasks = Task.objects.filter(wastebasket__exact=wastebasket_model)
    
    working_tasks = []
    for task in tasks:
        if task.state == TaskState.WORKING:
            working_tasks.append(task)
    
    return working_tasks


def restore_worker(result, wb, paths):
    """Function for parallel restoring files."""
    result.extend(wb.restore(*paths))


def remove_worker(result, wb, paths):
    """Function for restoring files."""
    result.extend(wb.remove(*paths))

wastebasket/templates/wastebasket/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <title>
            {% block title %}
            {% endblock %}
        </title>

        <!-- Bootstrap CSS --> 
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    </head>

    <body>
        <nav class="navbar navbar-toggleable-md navbar-inverse" style="background-color: #092E20;">
            {% block top_menubar %}{% endblock %}
        </nav>

        <div class="container-fluid">
            <div class="row">
                {% block content %}{% endblock %}
            </div>
        </div>
        
        <!-- jQuery first, then Tether, then Bootstrap JS. -->
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    </body>
</html>

wastebasket/templates/wastebasket/home.html
{% extends "wastebasket/base.html" %}

{% block title %}Home{% endblock %}

{% block top_menubar %}
    <a class="navbar-brand" href= {% url 'wastebasket:wastebasket_list' %}>Wastebaskets</a>
    <a class="navbar-brand" href= {% url 'wastebasket:task_list' %}>Tasks</a>
{% endblock %}

wastebasket/templates/wastebasket/task_detail.html
{% extends "wastebasket/home.html" %}

{% block title %} 
    {{ form.name.value }}
{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}

            <table class="table">{{ form.as_table }}</table>

            <button type="submit" class="btn btn-primary">
                Save
            </button>  
        </form>
    </div>
{% endblock %}

wastebasket/templates/wastebasket/task_list.html
{% extends "wastebasket/home.html" %}

{% block title %}Task list{% endblock %}

{% block top_menubar %}
    {{ block.super }}
    <a class="navbar-brand navbar-toggler-right"  href= {% url 'wastebasket:task_new' %}>Add</a>
{% endblock %}

{% block content %}
    {% if tasks %}
        <table class="table">
            <thead>
                <th>Name</th>
                <th>Wastebasket</th>
                <th>Rmdir</th>
                <th>Force</th>
                <th>Dry-run</th>
                <th>Restore</th>
                <th>Regex</th>
                <th>Run</th>
            </thead>

            <tbody>
                {% for task in tasks %}
                    <tr>
                        <td><a href= {% url 'wastebasket:task_detail' task.pk %}>{{ task }}</a></td>
                        <td>{{ task.wastebasket }}</td>
                        <td>{{ task.rmdir }}</td>
                        <td>{{ task.force }}</td>
                        <td>{{ task.dry_run }}</td>
                        <td>{{ task.restore }}</td>
                        <td>{{ task.regex }}</td>
                        <td><a href= {% url 'wastebasket:task_result' task.pk %}>RUN</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-warning" role="alert">
            <strong>Warning!</strong> No tasks found :(
        </div>
    {% endif %}

{% endblock %}

wastebasket/templates/wastebasket/task_new.html
{% extends "wastebasket/home.html" %}

{% block title %}New task{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}

            <table class="table">
                {{ form.as_table }}
            </table>

            <button type="submit" class="btn btn-primary">
                Save
            </button>
         
        </form>
    </div>
{% endblock %}

wastebasket/templates/wastebasket/task_result.html
{% extends "wastebasket/home.html" %}

{% block title %}Result{% endblock %} 

{% block content %}
    <table class="table">
        <thead>
            <th>Action</th>
            <th>Old path</th>
            <th>New path</th>
        </thead>

        <tbody>
            {% for src, dst in result %}
                <tr>
                    <td>{{ action }}</td>
                    <td>{{ src }}</td>
                    <td>{{ dst }}</td>
                </tr>
            {% endfor %}  
        </tbody>
    </table>

        {% if task %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> For "{{ task.wastebasket }}" the task is already running: {{ task.name }}
            </div>
        {% elif error_object %}
            <div class="alert alert-danger" role="alert">
                <strong>Error!</strong> {{ error_object.message }} "{{ error_object.raised_path }}".
            </div>
        {% endif %}
{% endblock %} 

wastebasket/templates/wastebasket/wastebasket_detail.html
{% extends "wastebasket/wastebasket_list.html" %}

{% block detail %}
    <div class="container-fluid">
        <div class="row">
            <form method="POST">
                {% csrf_token %}
              
                <div class="col-xl-6">
                    <table class="table">{{ form.as_table }}</table>

                    <button type="submit" class="btn btn-primary">
                        Save
                    </button>
                </div>
            </form>

            <div class="col-xl-6">
                <h2>Content:</h2>  
                <ul class="list-group">
                    {% for path in wastebasket.content %}
                        <li class="list-group-item">{{ path }}</li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>
{% endblock %}

wastebasket/templates/wastebasket/wastebasket_list.html
{% extends "wastebasket/home.html" %}

{% block title %}Wastebasket list{% endblock %}

{% block top_menubar %}
    {{ block.super }}
    <a class="navbar-brand navbar-toggler-right"  href= {% url 'wastebasket:wastebasket_new' %}>Add</a>
{% endblock %}

{% block content %}
    {% if wastebaskets %}
        <nav class="col-xl-1 bg-faded sidebar">
            <ul class="nav nav-pills flex-column">
            {% for wb in wastebaskets %}
                <li class="nav-item">
                    <a class="nav-link" href= {% url 'wastebasket:wastebasket_detail' wb.pk %}>
                        {{ wb }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </nav>
    {% else %}
        <div class="alert alert-warning" role="alert">
            <strong>Warning!</strong> No wastebaskets found :(
        </div>
    {% endif %}

    <div class="col-xl-11">
        {% block detail %}{% endblock %}
    </div>
{% endblock %}

wastebasket/templates/wastebasket/wastebasket_new.html
{% extends "wastebasket/home.html" %}
    
{% block title %}New wastebasket{% endblock %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            
            <table class="table">{{ form.as_table }}</table>

            <button type="submit" class="btn btn-primary">
                Save
            </button>
        </form>
    </div>
{% endblock %}